#-----------------------------------------------------------------------------------------------#
#     _____  _          __      ________ _____    __  __          _____  _  ________ _______    #
#    |  __ \| |        /\\ \   / /  ____|  __ \  |  \/  |   /\   |  __ \| |/ /  ____|__   __|   #
#    | |__) | |       /  \\ \_/ /| |__  | |__) | | \  / |  /  \  | |__) | ' /| |__     | |      #
#    |  ___/| |      / /\ \\   / |  __| |  _  /  | |\/| | / /\ \ |  _  /|  < |  __|    | |      #
#    | |    | |____ / ____ \| |  | |____| | \ \  | |  | |/ ____ \| | \ \| . \| |____   | |      #
#    |_|    |______/_/    \_\_|  |______|_|  \_\ |_|  |_/_/    \_\_|  \_\_|\_\______|  |_|      #
#                                                                                               #
#-----------------------------------------------------------------------------------------------#

# PlayerMarket by Norbit4

# github: https://github.com/Norbit4
# modrinth: https://modrinth.com/user/norbit
# spigot: https://www.spigotmc.org/resources/authors/norbittech.392197/
# builtbybit: https://builtbybit.com/creators/n0rbit.98575/

# If you like the plugin, support me with a positive opinion <3

# Need support?
# wiki: https://github.com/Norbit4/PlayerMarket
# Join to discord: https://discord.com/invite/DPXqQcDDTs

#---------------------------------------#
#              [ config ]               #
#---------------------------------------#

# HEX CODES SUPPORTED
# &<code> ex. &#ff5733
# https://htmlcolorcodes.com/

# advanced logs
debug: false

#---------------------------------------#
#             [ DATABASE ]              #
#---------------------------------------#
# mysql/h2
database:
  type: 'h2'
  database: 'playermarket'
  host: 'jdbc:mysql://localhost:3306'
  user: 'root'
  password: 'password'
  use-ssl: false

#---------------------------------------#
#             [ COMMANDS ]              #
#---------------------------------------#

# /playermarket - help command
# /playermarket reload - reload plugin
# /playermarket clear <player> - clear player data

main-command:
  # permission: playermarket.command.main.clear
  clear:
    success: '<gray>Data for <yellow>{player} <gray>has been cleared!'
    player-not-found: '<red>Player not found!'
  # permission: playermarket.command.main.help
  help:
    info:
      - '<dark_gray>--------------- <green><bold>PLAYERMARKET <dark_gray>---------------'
      - ''
      - '<gray><bold>» <dark_gray><bold>/<green>market <gray>- <white>Open the market!'
      - '<gray><bold>» <dark_gray><bold>/<green>offer [cost] <gray>- <white>Offer an item!'
  # permission: playermarket.command.main.reload
  reload:
    success: '<green>Plugin has been reloaded!'
    # display in help when player has permission
    info:
      - '<gray><bold>» <dark_gray><bold>/<green>playermarket reload <gray>- <white>Reload files!'
      - '<gray><bold>» <dark_gray><bold>/<green>playermarket clear [player] <gray>- <white>Clear player data!'
      - ''

# /offer <price> - offer an item
offer-command:
  # Requires a server restart after changing this value.
  prefix: 'offer'
  argument-name: 'price'
  use-permission:
    enabled: false
    permission: 'playermarket.command.offer'
  usage: '<red>Usage: /offer [price]'
  wrong-price: '<red>The price variable is invalid!'
  wrong-item: '<red>You can not offer this item!'
  success: '<green>You have successfully offered this item!'

# /market - open market
market-command:
  # Requires a server restart after changing this value.
  prefix: 'market'
  use-permission:
    enabled: false
    permission: 'playermarket.command.market'

#---------------------------------------#
#              [ GLOBAL ]               #
#---------------------------------------#

# Plugin support economy:
#  Vault - https://www.spigotmc.org/resources/vault.34315/
#  PlayerPoints - https://www.spigotmc.org/resources/playerpoints.80745/

# Economy configuration
# type:
#  - Vault -> uses a Vault economy from server plugins
#  - PlayerPoints -> uses PlayerPoints plugin
economy:
  type: 'Vault'

expire:
  # expire time in minutes
  # 0 - never expire
  time: 10080 # 7 days
  status: '<red>Expired!'
  never: '<light_purple>Never'
  message: '<red>This offer has expired!'
  prefix:
    days: 'd'
    hours: 'h'
    minutes: 'm'
    # seconds show up when expiration time is less than an hour
    seconds: 's'

# tax system, tax will be taken from the seller
tax:
  # tax in percent
  enabled: false
  # tax value must be between 0 and 1
  # 0.15 = 15%
  value: 0.15
  # tax command executed when player buy item, {cost} - tax money value
  command:
    enabled: false
    execute: 'eco give Norbit4 {cost}' # example: add tax money to a server owner

blacklist:
  # Item identifier.
  # Supports vanilla Minecraft materials and custom items.
  #
  # Formats:
  # - <material>               (Vanilla Minecraft)
  # - nexo:<id>                (Nexo)
  # - ia:<id>                  (ItemsAdder)
  # - mmoitems:<category>:<id> (MMOItems)
  # - oraxen:<id>              (Oraxen)
  # - ce:<id>                  (CraftEngine)
  # - mm:<id>                  (MythicMobs)
  #
  # Examples:
  # - STONE
  # - DIAMOND_SWORD
  # - nexo:ruby
  # - ia:magic_ingot
  # - mmoitems:SWORD:LONG_SWORD
  # - oraxen:amethyst_hammer
  # - ce:topaz
  # - mm:BanditTunic

  # if enabled, players will not be able to offer items from this list
  enabled: false
  # If enabled, the list acts as a whitelist instead.
  # Only items from the list can be offered.
  whitelist-mode: false
  message: '<red>You can not offer this item!'
  # items in blacklist, you can use item ids or names
  items:
    - 'DIAMOND_SWORD' # example of item id
    - 'test item' # example of item name

offers-limit:
  enabled: true
  default-limit: 4
  # usage:
  # ex. 'playermarket.offers.limit.15' => 15 offers
  permission: 'playermarket.offers.limit'
  limit-message: '<red>You have reached maximum amount of active offers!'

cooldown:
  # Cooldown for commands and some GUI icons (in milliseconds, recommended: 400–500)
  # This value helps protect the system from excessive spam.
  # Significantly lowering this value is strongly discouraged.
  time: 400
  # Maximum number of clicks allowed per second in GUI (recommended: 5–7)
  #  This value helps protect the GUI from spam clicking.
  #  Significantly increasing this value is strongly discouraged.
  clicks-per-second: 7

# {date} - item offer date
# {cost} - item price
# {seller} - item seller
# {expire} - item expire time
market-offer-item-lore:
  - '<italic><dark_gray>{date}'
  - ''
  - '<!italic><white><sprite:"minecraft:gui":"icon/trial_available"> Cost: <#ADFF85>{cost}$'
  - '<!italic><white><head:{seller}> Seller: <#F5FF85>{seller}'
  - '<!italic><white><sprite:"minecraft:items":"item/clock_14"> Expire: <#F599FF>{expire}'
  - ''
  - '<!italic><#dcee9a>Click to buy!'

# Icon for not empty shulker box
market-offer-shulker-lore:
  - '<italic><dark_gray>{date}'
  - ''
  - '<!italic><white><sprite:"minecraft:gui":"icon/trial_available"> Cost: <#ADFF85>{cost}$'
  - '<!italic><white><head:{seller}> Seller: <#F5FF85>{seller}'
  - '<!italic><white><sprite:"minecraft:items":"item/clock_14"> Expire: <#F599FF>{expire}'
  - ''
  - '<!italic><#dcee9a>[LPM] Click to buy!'
  - '<!italic><#dcee9a>[PPM] Click to preview!'

# {date} - item offer date
# {cost} - item price
# {expire} - item expire time
player-offer-item-lore:
  - '<italic><dark_gray>{date}'
  - ''
  - '<!italic><white><sprite:"minecraft:gui":"icon/trial_available"> Cost: <#ADFF85>{cost}$'
  - '<!italic><white><sprite:"minecraft:items":"item/clock_14"> Expire: <#F599FF>{expire}'
  - ''
  - '<!italic><#dcee9a>Click to delete!'

player-offer-shulker-lore:
  - '<italic><dark_gray>{date}'
  - ''
  - '<!italic><white><sprite:"minecraft:gui":"icon/trial_available"> Cost: <#ADFF85>{cost}$'
  - '<!italic><white><sprite:"minecraft:items":"item/clock_14"> Expire: <#F599FF>{expire}'
  - ''
  - '<!italic><#dcee9a>[LPM] Click to delete!'
  - '<!italic><#dcee9a>[PPM] Click to preview!'

#---------------------------------------#
#               [ INFO ]                #
#---------------------------------------#
info-messages:
  cooldown: '<red>Slow down! You need wait a moment!'
  join: '<gray>You have <green>{money}$ <gray>to collect for <green>{sold} <gray>sold items <green>/market'

#---------------------------------------#
#             [ DISCORD ]               #
#---------------------------------------#
# Discord Webhook Logs
discord:
  enabled: false
  webhook-url: ''
  messages:
    # {player} - player name
    # {item} - item material
    # {cost} - item price
    # {seller} - item seller
    buy:
      enabled: true
      color: 65280 # GREEN
      message: 'Player **{player}** bought **{item}** for **{cost}$** from **{seller}**'
    offer:
      enabled: true
      color: 16776960 # YELLOW
      message: 'Player **{seller}** offered **{item}** for **{cost}$**'

#---------------------------------------#
#            [ MARKET - GUI ]           #
#---------------------------------------#

# Item identifier.
# Supports vanilla Minecraft materials and custom items.
#
# Formats:
# - <material>               (Vanilla Minecraft)
# - nexo:<id>                (Nexo)
# - ia:<id>                  (ItemsAdder)
# - mmoitems:<category>:<id> (MMOItems)
# - oraxen:<id>              (Oraxen)
# - ce:<id>                  (CraftEngine)
# - mm:<id>                  (MythicMobs)
#
# Examples:
# - STONE
# - DIAMOND_SWORD
# - nexo:ruby
# - ia:magic_ingot
# - mmoitems:SWORD:LONG_SWORD
# - oraxen:amethyst_hammer
# - ce:topaz
# - mm:BanditTunic
market-gui:
  title: '<dark_gray><bold>MARKET <gray><bold>» <dark_gray><bold>{category} ({current}/{total})'
  fill: false # if true, all empty slots will be filled with border icons, ignores border layout
  size: 6 # in rows
  border-icon:
    name: ' '
    icon: 'GRAY_STAINED_GLASS_PANE'
    lore: []
  your-offers-icon:
    name: '<#93f182><bold>YOUR OFFERS'
    icon: 'CHEST'
    slot: 49
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  search-icon:
    name: '<#93f182><bold>SEARCH'
    icon: 'NAME_TAG'
    slot: 51
    enabled: true
    lore:
      - ''
      - '<gray>Type item name...'
      - ''
      - '<#dcee9a>Click to search!'
  previous-page-icon:
    name: '<white><bold>PREVIOUS PAGE'
    icon: 'ARROW'
    slot: 46
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  next-page-icon:
    name: '<white><bold>NEXT PAGE'
    icon: 'ARROW'
    slot: 52
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  layout:
    border:
      - 1
      - 10
      - 19
      - 28
      - 37
      - 7
      - 16
      - 25
      - 34
      - 43
      - 38-42
    items:
      - 2-6
      - 11-15
      - 20-24
      - 29-33
    categories:
      - 0
      - 8-9
      - 17-18
      - 26-27
      - 35-36
      - 44

#---------------------------------------#
#          [ BUY - MESSAGES ]           #
#---------------------------------------#
buy-messages:
  item-sold-message: '<red>This offer is already sold!'
  not-enough-money-message: '<red>You do not have enough money!'
  player-is-owner-message: '<red>You can not buy your own item!'
  success-message: '<white>You have bought an item for <green>{COST}$!'
  sell-item-to-owner: '<gray>Player <green>{player} <gray>bought your item for <green>{cost}$!'
  inventory-full-message: '<red>Your inventory is full!'

#---------------------------------------#
#       [ Dialog - INPUT - SEARCH ]       #
#---------------------------------------#

dialog-admin-delete:
  title: ''
  text-break: '\n\n\n\n\n\n\n\n\n\n\n\n'
  text-title: '<shadow:#0c0c0c:1><sprite:"minecraft:gui":"player_list/remove_player"> Delete an item</shadow>'
  text-info: '<shadow:#0c0c0c:1><sprite:"minecraft:gui":"icon/trial_available"> Cost: <#ADFF85>{cost}$\n <white><head:{seller}> Seller: <#F5FF85>{seller}</shadow>'
  back-button: '<white>Back'
  accept-button: '<white>Delete'

dialog-buy:
  title: ''
  text-break: '\n\n\n\n\n\n\n\n\n\n\n\n'
  text-title: '<shadow:#0c0c0c:1><sprite:"minecraft:gui":"icon/checkmark"> Purchase an item</shadow>'
  text-info: '<shadow:#0c0c0c:1><sprite:"minecraft:gui":"icon/trial_available"> Cost: <#ADFF85>{cost}$\n <white><head:{seller}> Seller: <#F5FF85>{seller}</shadow>'
  back-button: '<white>Back'
  accept-button: '<white>Confirm'

dialog-input:
  title: ''
  text-break: '\n\n\n\n\n\n\n\n\n\n\n\n'
  text-label: '<white>Type item name'
  back-button: '<white> Back'
  search-button: '<white> Search'

#---------------------------------------#
#            [ SEARCH - GUI ]           #
#---------------------------------------#
search-gui:
  title: '<dark_gray><bold>SEARCH <gray><bold>» <dark_gray><bold>{search} ({current}/{total})'
  size: 6 # in rows
  fill: false # if true, all empty slots will be filled with border icons, ignores border layout
  border-icon:
    name: ' '
    icon: 'GRAY_STAINED_GLASS_PANE'
    lore: []
  back-to-market-icon:
    name: '<#93f182><bold>BACK TO MARKET'
    icon: 'BARRIER'
    slot: 49
    lore:
      - ''
      - '<#dcee9a>Click to go back!'
  previous-page-icon:
    name: '<white><bold>PREVIOUS PAGE'
    icon: 'ARROW'
    slot: 45
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  next-page-icon:
    name: '<white><bold>NEXT PAGE'
    icon: 'ARROW'
    slot: 53
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  layout:
    border:
      - 36-44
    items:
      - 0-35

#---------------------------------------#
#            [ OFFERS - GUI ]           #
#---------------------------------------#
offers-gui:
  title: '<dark_gray><bold>YOUR OFFERS'
  size: 6 # in rows
  fill: false # if true, all empty slots will be filled with border icons, ignores border layout
  remove-offer-message: '<red>Your offer has been removed!'
  nothing-to-get-message: '<red>You have nothing to claim!'
  inventory-full-message: '<red>Your inventory is full!'
  success-message: '<green>You have successfully received <dark_green>{money}$ <green>for your sold offers!'
  border-icon:
    name: ' '
    icon: 'GRAY_STAINED_GLASS_PANE'
    lore: []
  statistics-icon:
    name: '<#93f182><bold>YOUR ACCOUNT'
    icon: 'CHEST'
    slot: 4
    lore:
      # {offers} - player offers
      # {offers_limit} - player offers limit
      # {money_earned} - player money earned
      # {all_sold} - all time player sold items
      # {all_money_earned} - all time player money earned
      - ''
      - '<aqua>◆ <white>Offers: <aqua>{offers}<dark_gray>/<aqua>{offers_limit}'
      - '<light_purple>◆ <white>Sold offers: <light_purple>{sold}'
      - '<green>$ <white>Money to claim: <green>{money_earned}$'
      - ''
      - '<light_purple>◆ <white>All time sold offers: <light_purple>{all_sold}'
      - '<green>$ <white>All time money earned: <green>{all_money_earned}$'
      - ''
      - '<#dcee9a>Click to claim!'
  back-to-market-icon:
    name: '<#93f182><bold>BACK TO MARKET'
    icon: 'BARRIER'
    slot: 49
    lore:
      - ''
      - '<#dcee9a>Click to go back!'
  previous-page-icon:
    name: '<white><bold>PREVIOUS PAGE'
    icon: 'ARROW'
    slot: 46
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  next-page-icon:
    name: '<white><bold>NEXT PAGE'
    icon: 'ARROW'
    slot: 52
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  layout:
    border:
      - 36-44
    items:
      - 10-16
      - 19-25
      - 28-34

#---------------------------------------#
#         [ SHULKERBOX - GUI ]          #
#---------------------------------------#
# shulker box gui, opens when player click shulker box for preview

shulker-gui:
  title: '<dark_gray><bold>ITEM PREVIEW'
  fill: false # if true, all empty slots will be filled with border icons, ignores border layout
  item-sold-message: '<red>This offer is already sold!'
  border-icon:
    name: ' '
    icon: 'GRAY_STAINED_GLASS_PANE'
    lore: []
  back-icon:
    name: '<#93f182><bold>BACK'
    icon: 'BARRIER'
    slot: 40
    lore:
      - ''
      - '<#dcee9a>Click to go back!'
  buy-icon:
    name: '<#93f182><bold>BUY'
    icon: 'GREEN_WOOL'
    slot: 36
    lore:
      - ''
      - '<#dcee9a>Click to buy!'

#---------------------------------------#
#            [ CATEGORIES ]             #
#---------------------------------------#
category-name-format: '<#93f182><bold>{category}'
category-selected-lore:
  - ''
  - '<green><bold>Selected!'

# all items without category will go to this category
other-category:
  # if disabled, all items without category will be not available to buy in shop
  enabled: true
  name: "OTHER"
  icon: "ENDER_PEARL"
  lore:
    - ''
    - '<#dcee9a>Click to browse!'

# main page category, all items will be displayed here
all-category:
  enabled: true
  name: "MAIN"
  icon: "NETHER_STAR"
  lore:
    - ''
    - '<#dcee9a>Click to browse!'
    -

# categories, you can add more categories
# file is the name of the file /categories/<file>.yml
categories:
  1:
    name: 'BLOCKS'
    icon: 'BRICKS'
    file: 'blocks'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  2:
    name: 'ARMOR'
    icon: 'DIAMOND_CHESTPLATE'
    file: 'armor'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  3:
    name: 'COMBAT'
    icon: 'GOLDEN_SWORD'
    file: 'combat'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  4:
    name: 'MINERALS'
    icon: 'AMETHYST_SHARD'
    file: 'minerals'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  5:
    name: 'NATURE'
    icon: 'BAMBOO'
    file: 'nature'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  6:
    name: 'REDSTONE'
    icon: 'REDSTONE'
    file: 'redstone'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  7:
    name: 'TOOLS'
    icon: 'IRON_PICKAXE'
    file: 'tools'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'
  8:
    name: 'FOOD'
    icon: 'ENCHANTED_GOLDEN_APPLE'
    file: 'food'
    lore:
      - ''
      - '<#dcee9a>Click to browse!'