name: PlayerMarket
version: '${version}'
main: pl.norbit.playermarket.PlayerMarket
authors: [Norbit4]
website: https://n0rbit.pl/
api-version: 1.16

softdepend:
  - PlayerPoints
  - Vault
  - PlaceholderAPI