name: PlayerMarket
version: '${version}'
main: pl.norbit.playermarket.PlayerMarket
authors: [Norbit4]
website: https://github.com/Norbit4
api-version: 1.21
softdepend:
  - PlayerPoints
  - Vault
  - PlaceholderAPI
  - ItemsAdder
  - Oraxen
  - Nexo
  - MMOItems
  - MythicMobs
  - CraftEngine
libraries:
  - mysql:mysql-connector-java:8.0.33
  - commons-dbutils:commons-dbutils:1.7
  - com.h2database:h2:2.2.220
  - org.yaml:snakeyaml:2.0
commands:
    playermarket:
        description: Help command
        usage: /playermarket